name: C/C++ CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: dependencies  
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev build-essential git net-tools libncurses5-dev libncursesw5-dev libpcre2-dev libpcap-dev cmake zlib1g-dev
    - name: Checkout repository
      run: git clone --recurse-submodules https://github.com/LTNGlobal-opensource/libatsc3.git --branch develop
    - name: build
      run: cd ./libatsc3/src && ./build_linux.sh 
    - name: prepare artifacts
      run: mkdir binaries && cp libatsc3/src/listenter_tests/atsc3_stltp_alp_listener_reflector_test binaries && cp libatsc3/src/tools/atsc3_alc_listener_mde_writer binaries
    - uses: actions/upload-artifact@v2
      with:
        name: libatsc3-artifact
        path: |
          binaries/*
